### ISSUE TITLE
Updates required for pimatc 0.9

### ISSUE THREAD

**Issue by mwittig** [Timvdv/pimatic-quote-of-the-day#1]
A couple of changes to your package are required to make it run with the upcoming pimatic release version 0.9. I'll file a pull request with the necessary changes shortly.

I also had to add the missing "request" package  dependency to make it run. I also noticed an inconstistency in the license info you provide. The LICENSE is GPL-2.0 but in the package descriptor you set it to ISC. I have changed that GPL-2.0. Just skip or revert in case you want this to be ISC and replace the license file.

I did not get the purpose of the `url_encoded_quote` attribute. What do you use it for?

**Comment by Timvdv** [comment]
GPL-2.0 license is fine :)

I used the `url_encoded_quote` in a post request via a rule and that wouldn't accept spaces but I use an alternative method right now so I removed it from the code! Thanks for the tips & changes
